env:
    browser: true
    es2021: true
    jest: true

extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier

overrides:
    - files:
          - '*.ts'

      parser: '@typescript-eslint/parser'

      parserOptions:
          ecmaVersion: latest
          sourceType: module

      plugins:
          - '@typescript-eslint'
          - prettier

      settings:
          import/resolver:
              typescript: {}

      rules:
          camelcase: error
          spaced-comment: error
          quotes: ['error', 'single']
          no-duplicate-imports: error
          '@typescript-eslint/no-unused-vars': ['warn', { 'argsIgnorePattern': 'dotenv' }]

    - files:
          - '*.json'

      rules:
          quotes: ['error', 'double']

ignorePatterns:
    - build
